language: python
python:
  - '3.6'

env:
  global:
    - CONDA_CHANNELS='conda-forge'
    - CONDA_CHANNEL_PRIORITY=True
    - CONDA_DEPENDENCIES='numpy cython yaehmop>=2019'
    - BUILD_CMD='pip install .'
    - SETUP_CMD='pytest'

install:
  - git clone --depth 1 git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install -c conda-forge --yes numpy cython yaehmop pytest
  - pip instal -U .

script:
  - pytest
