language: generic
python:
  - '3.6'

env:
  global:
    - CONDA_CHANNELS='conda-forge'
    - CONDA_CHANNEL_PRIORITY=True
    - CONDA_DEPENDENCIES='numpy cython yaehmop mdanalysis pytest-cov lapack blas'
    - MAIN_CMD='python setup.py develop'
    - SETUP_CMD='pytest --cov=pyyaehmop/ pyyaehmop/tests/'
    - CYTHON_TRACE_NOGIL=1

install:
  - git clone --depth 1 git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh

script:
  - $MAIN_CMD
  - $SETUP_CMD
